---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  type: ClusterIP
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 443
      protocol: UDP
      name: quic

