---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  type: ClusterIP
  ports:
    - port: 80
    - port: 443
    - port: 443
      protocol: UDP

