---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: caddy
  namespace: {{ $.Release.Namespace }}
  labels:
    app: caddy

spec:

  selector:
    matchLabels:
      app: caddy

  template:
    metadata:
      name: caddy
      labels:
        app: caddy

    spec:

      volumes:
        - name: data-volume
          hostPath:
            path: "{{ $.Values.DataDir }}"
        - name: config-volume
          hostPath:
            path: "{{ $.Values.ConfigDir }}"
        - name: etc-caddy-volume
          hostPath:
            path: "{{ $.Values.EtcCaddyDir }}"

      containers:

        - name: caddy
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameGithubCaddy }}:{{ $.Values.ImageTagGithubCaddy }}"
          envFrom:
            - configMapRef:
                name: caddy

          volumeMounts:
            - name: data-volume
              mountPath: /data/
            - name: config-volume
              mountPath: /config/
            - name: etc-caddy-volume
              mountPath: /etc/caddy/


